name: Build images

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: setup builder
      run: docker buildx create --name multi-arch --use --bootstrap --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8
      
    - name: build frontend
      run: docker buildx build --push --tag ${{env.IMAGE_NAME}}-web:latest frontend

    - name: build frontend-svelte
      run: docker buildx build --push --tag ${{env.IMAGE_NAME}}-web-sv:latest frontend-svelte

    - name: build backend
      run: docker buildx build --push --tag ${{env.IMAGE_NAME}}-api:latest backend
      
