name: Build images

on:
  push:
    branches: [ "main","ci" ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
      
    - name: Build and push frontend
      uses: docker/build-push-action@v6
      with:
        context: frontend-svelte
        file: frontend-svelte/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm64/v8
        push: true
        tags: ${{env.IMAGE_NAME}}-web-sv:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push backend
      uses: docker/build-push-action@v6
      with:
        context: backend
        file: backend/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm64/v8
        push: true
        tags: ${{env.IMAGE_NAME}}-api:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max     
