name: Build images

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build frontend
      run: docker build frontend --file frontend/Dockerfile --tag ${{env.IMAGE_NAME}}-web:latest

    - name: Build backend
      run: docker build backend --file backend/Dockerfile --tag ${{env.IMAGE_NAME}}-api:latest

    - name: Push frontend image
      run: docker push ${{env.IMAGE_NAME}}-web:latest

    - name: Push backend image
      run: docker push ${{env.IMAGE_NAME}}-api:latest
